---
name: Lint Code Base

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - "dependabot/npm_and_yarn/*"

jobs:
  build:
    # Name the Job
    name: Lint Code Base
    # Set the agent to run on
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          VALIDATE_MARKDOWN: true
          VALIDATE_PYTHON_PYLINT: true
          VALIDATE_PYTHON_FLAKE8: true
          VALIDATE_PYTHON_BLACK: true
          IGNORE_GENERATED_FILES: true
          IGNORE_GITIGNORED_FILES: true
          LINTER_RULES_PATH: /
          PYTHON_PYLINT_CONFIG_FILE: .pylintrc
          PYTHON_FLAKE8_CONFIG_FILE: .flake8
          PYTHON_BLACK_CONFIG_FILE: pyproject.toml
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Linting
          skip_fetch: true
